project:
  type: website
  output-dir: docs

website:
  title: "Chart & Chill 📊"
  navbar:
    left:
      - href: index.qmd
        text: "Startseite"
      - href: lektionen.qmd
        text: "Lektionen"
      - href: nonnegotiables.qmd
        text: "Non Negotiables😬"
      - href: links.qmd
        text: "Links"
      - href: galerie.qmd
        text: "Galerie"
      - href: ueber.qmd
        text: "Über"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
